[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://repo.prefix.dev/mojo-community", "https://repo.prefix.dev/jojo"]
description = "Add a short description here"
name = "jojo-cli"
platforms = ["osx-arm64",]
version = "0.1.0"

#
# 类似 rust cargo 的 [[bin]]
#
[tasks]
cli = "mojo src/main.mojo" # exec build
cli2 = "mojo src/main.mojo"


[dependencies]
max = ">=24.5.0,<25"
lightbug_http = ">=0.1.4,<0.2"
jojo_core = ">=0.1.3,<0.2"

