version: "3"

tasks:
  fmt:
    cmds:
      - magic run mojo format -l 120 .

  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}

  dev:
    aliases: [ 'd', ]
    cmds:
      - magic run mojo src/run.mojo

  package:
    aliases: [ "p", "pack" ]
    cmds:
      - mkdir -p build/
      - magic run mojo package src/ -o build/jojo-http.mojopkg

  venv:
    cmds:
      - magic shell
      - mojo --version
    ignore_error: true
