# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
    version: "13.4.2"

package:
    name: "jojo_core"
    version: 0.1.2

source:
    - path: ../src/

build:
    script:
        - mkdir -p ${PREFIX}/lib/mojo
        - magic run mojo package . -o ${PREFIX}/lib/mojo/jojo_core.mojopkg

requirements:
    run:
        - max >=24.5.0
#        - gojo == 0.1.9

about:
    homepage: https://github.com/better-mojo/jojo
    license: MIT
    summary: "Core library for Jojo web framework - better-mojo"
    repository: https://github.com/better-mojo/jojo
